# Generated by Django 2.1.5 on 2019-02-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributename',
            name='zobrazit',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
