# Generated by Django 2.1.5 on 2019-02-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190208_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='obrázek_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
